spring:
  datasource:
    url: jdbc:postgresql://db:5432/request
    username: postgres
    password: qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB